site_name: cp-algorithms
docs_dir: src
theme:
  name: material
repo_url: https://github.com/e-maxx-eng/e-maxx-eng
edit_uri: edit/master/src/
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
